server:
  port: 11500

spring:
  application:
    name: client-api
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.33.3:8848
        namespace: c4095cdf-b3cf-48eb-9706-d6335699b584
      config:
        server-addr: 175.178.33.3:8848
        group: DEFAULT_GROUP
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.33.3:3306/crazyNetDisk?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 3236588wwwWWW!
mybatis:
  mapper-locations: classpath:mapper/*.xml
crazy:
  netDisk:
    config:
      sysAdmin-userId: crazypang
